### ISSUE TITLE
VG as absolute path

### ISSUE THREAD

**Issue by ic248** [puppetlabs/puppetlabs-lvm#295]
Hi,

While submitting the other bug report I noticed that the data type for vg in lvm::volume is now Stdlib::Absolutepath. As far as I'm aware a volume group is just a string not a path? Below is an example of what we currently set for a test server and it will error out on vg.

`Evaluation Error: Error while evaluating a Resource Statement, Lvm::Volume[reports]: parameter 'vg' expects a Stdlib::Absolutepath = Variant[Stdlib::Windowspath = Pattern[/\A(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+)).*\z/], Stdlib::Unixpath = Pattern[/\A\/([^\n\/\0]+\/*)*\z/]] value, got String`

```
lvm::volume:
    reports:
        ensure: present
        vg: 'vg_reports'
        pv: '/dev/sdb'
        fstype: 'xfs'
        size: '200G'
```

The example in Puppet Forge (below) also shows it as a string.

`lvm::volume { 'lv_example0': vg => 'vg_example0', pv => '/dev/sdd1', fstype => 'ext4', size => '100GB', }`

Please say if you require any more info.

Thanks
Ian
