### ISSUE TITLE
vgcreate fails if physical_volumes is a hash

### ISSUE THREAD

**Issue by andylytical** [puppetlabs/puppetlabs-lvm#315]
## Describe the Bug
If the PV and VG don't exist yet and physical_volumes is a hash, throws this error:
```
Error: Execution of '/usr/sbin/vgcreate vg_backups {"/dev/sdc"=>{"unless_vg"=>"vg_backups"}}' returned 5: No device found for {"/dev/sdc"=>{"unless_vg"=>"vg_backups"}}.
```

## Expected Behavior
Expect PV and VG creation to succeed.

## Steps to Reproduce
1. Hiera data:
```
lvm::volume_groups:
  vg_backups:
    createonly: true
    physical_volumes:
      /dev/sdc:
        unless_vg: "vg_backups"
    logical_volumes:
      backups:
        fs_type: "xfs"
        mountpath: "/backups"
```
2. Puppet module:
```
include ::lvm
```
5. Run puppet

## Environment
 - Version `2.0.3`
 - Platform `Red Hat Enterprise Linux 9.2 (Plow)`
 - Puppet version `7.26.0`
