### ISSUE TITLE
Catalog compilation fails with: no parameter named 'yes_flag'

### ISSUE THREAD

**Issue by andylytical** [puppetlabs/puppetlabs-lvm#316]
## Describe the Bug
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'yes_flag' (file: /etc/puppetlabs/code/environments/SVCPLAN_3734_jsm_setup/modules/lvm/manifests/logical_volume.pp, line: 126) on Logical_volume[backups]
```

## Expected Behavior
Puppet should compile the catalog and create the LV.

## Steps to Reproduce
1. Heira data:
```
lvm::volume_groups:
  vg_backups:
    createonly: true
    physical_volumes:
      /dev/sdc:
        unless_vg: "vg_backups"
    logical_volumes:
      backups:
        fs_type: "xfs"
        mountpath: "/backups"
```

2. Puppet module:
```
include ::lvm
```

3. Run puppet

## Environment
 - Version `2.0.3`
 - Platform `Red Hat Enterprise Linux 9.2 (Plow)`
 - Puppet version `7.26.0`

## Additional Context
This is possible only after fixing #315, which I think I have a fix for (https://github.com/ncsa/puppet-lvm/tree/aloftus/fix_pvcreate), but now running into this issue.
